BEGIN;

ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS reversion_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sales_reversion_version_check'
      AND conrelid = 'public.sales'::regclass
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_reversion_version_check
      CHECK (reversion_version IN (0, 1));
  END IF;
END
$$;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS sale_id integer,
  ADD COLUMN IF NOT EXISTS reversed_movement_id integer;

ALTER TABLE public.movimientos_financieros
  ADD COLUMN IF NOT EXISTS reversed_movement_id integer,
  ADD COLUMN IF NOT EXISTS sale_cancellation_id integer;

CREATE TABLE IF NOT EXISTS public.sale_stock_allocations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id integer NOT NULL,
  product_id integer NOT NULL,
  purchase_invoice_item_id integer,
  stock_movement_id integer,
  source_type text NOT NULL,
  cantidad integer NOT NULL,
  costo_unitario numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sale_stock_allocations_source_type_check
    CHECK (source_type IN ('purchase_invoice_item', 'product_cost', 'supplier_delivery')),
  CONSTRAINT sale_stock_allocations_cantidad_check
    CHECK (cantidad > 0),
  CONSTRAINT sale_stock_allocations_costo_check
    CHECK (costo_unitario >= 0)
);

CREATE TABLE IF NOT EXISTS public.sale_payment_allocations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id integer NOT NULL,
  movimiento_financiero_id integer NOT NULL,
  monto numeric NOT NULL,
  allocation_type text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sale_payment_allocations_monto_check
    CHECK (monto > 0),
  CONSTRAINT sale_payment_allocations_type_check
    CHECK (allocation_type IN ('initial_payment', 'client_payment', 'customer_order_payment')),
  CONSTRAINT sale_payment_allocations_sale_movement_key
    UNIQUE (sale_id, movimiento_financiero_id)
);

CREATE TABLE IF NOT EXISTS public.sale_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  estado_original text,
  total_original numeric NOT NULL,
  monto_pagado_original numeric NOT NULL,
  monto_pendiente_original numeric NOT NULL,
  costo_total_original numeric NOT NULL,
  ganancia_original numeric NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT sale_cancellations_sale_key UNIQUE (sale_id),
  CONSTRAINT sale_cancellations_motivo_check CHECK (length(trim(motivo)) >= 3)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'stock_movimientos_sale_id_fkey'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_sale_id_fkey
      FOREIGN KEY (sale_id) REFERENCES public.sales(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'stock_movimientos_reversed_movement_id_fkey'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_reversed_movement_id_fkey
      FOREIGN KEY (reversed_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_stock_allocations_sale_id_fkey'
      AND conrelid = 'public.sale_stock_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_stock_allocations
      ADD CONSTRAINT sale_stock_allocations_sale_id_fkey
      FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_stock_allocations_product_id_fkey'
      AND conrelid = 'public.sale_stock_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_stock_allocations
      ADD CONSTRAINT sale_stock_allocations_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES public.products(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_stock_allocations_purchase_item_id_fkey'
      AND conrelid = 'public.sale_stock_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_stock_allocations
      ADD CONSTRAINT sale_stock_allocations_purchase_item_id_fkey
      FOREIGN KEY (purchase_invoice_item_id) REFERENCES public.purchase_invoice_items(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_stock_allocations_stock_movement_id_fkey'
      AND conrelid = 'public.sale_stock_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_stock_allocations
      ADD CONSTRAINT sale_stock_allocations_stock_movement_id_fkey
      FOREIGN KEY (stock_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_payment_allocations_sale_id_fkey'
      AND conrelid = 'public.sale_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_payment_allocations
      ADD CONSTRAINT sale_payment_allocations_sale_id_fkey
      FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_payment_allocations_movement_id_fkey'
      AND conrelid = 'public.sale_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_payment_allocations
      ADD CONSTRAINT sale_payment_allocations_movement_id_fkey
      FOREIGN KEY (movimiento_financiero_id) REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_cancellations_sale_id_fkey'
      AND conrelid = 'public.sale_cancellations'::regclass
  ) THEN
    ALTER TABLE public.sale_cancellations
      ADD CONSTRAINT sale_cancellations_sale_id_fkey
      FOREIGN KEY (sale_id) REFERENCES public.sales(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_reversed_movement_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_reversed_movement_id_fkey
      FOREIGN KEY (reversed_movement_id) REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_sale_cancellation_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_sale_cancellation_id_fkey
      FOREIGN KEY (sale_cancellation_id) REFERENCES public.sale_cancellations(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_sale_id
  ON public.stock_movimientos (sale_id);

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_reversed_movement_id
  ON public.stock_movimientos (reversed_movement_id);

CREATE INDEX IF NOT EXISTS idx_sale_stock_allocations_sale_id
  ON public.sale_stock_allocations (sale_id);

CREATE INDEX IF NOT EXISTS idx_sale_stock_allocations_product_id
  ON public.sale_stock_allocations (product_id);

CREATE INDEX IF NOT EXISTS idx_sale_stock_allocations_purchase_item_id
  ON public.sale_stock_allocations (purchase_invoice_item_id);

CREATE INDEX IF NOT EXISTS idx_sale_stock_allocations_stock_movement_id
  ON public.sale_stock_allocations (stock_movement_id);

CREATE INDEX IF NOT EXISTS idx_sale_payment_allocations_sale_id
  ON public.sale_payment_allocations (sale_id);

CREATE INDEX IF NOT EXISTS idx_sale_payment_allocations_movement_id
  ON public.sale_payment_allocations (movimiento_financiero_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_reversed_movement_id
  ON public.movimientos_financieros (reversed_movement_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_sale_cancellation_id
  ON public.movimientos_financieros (sale_cancellation_id);

COMMIT;
