BEGIN;

ALTER TABLE public.purchase_invoices
  ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'Activa',
  ADD COLUMN IF NOT EXISTS reversion_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'purchase_invoices_reversion_version_check'
      AND conrelid = 'public.purchase_invoices'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoices
      ADD CONSTRAINT purchase_invoices_reversion_version_check
      CHECK (reversion_version IN (0, 1));
  END IF;
END
$$;

ALTER TABLE public.purchase_invoice_items
  ADD COLUMN IF NOT EXISTS previous_product_cost numeric,
  ADD COLUMN IF NOT EXISTS product_was_created boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS stock_movement_id integer;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS purchase_invoice_id integer,
  ADD COLUMN IF NOT EXISTS purchase_invoice_item_id integer;

ALTER TABLE public.movimientos_financieros
  ADD COLUMN IF NOT EXISTS purchase_invoice_id integer,
  ADD COLUMN IF NOT EXISTS purchase_invoice_cancellation_id integer;

ALTER TABLE public.cheques
  ADD COLUMN IF NOT EXISTS purchase_invoice_id integer;

CREATE TABLE IF NOT EXISTS public.purchase_invoice_payment_allocations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_invoice_id integer NOT NULL,
  movimiento_financiero_id integer NOT NULL,
  monto numeric NOT NULL,
  allocation_type text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_invoice_payment_allocations_monto_check
    CHECK (monto > 0),
  CONSTRAINT purchase_invoice_payment_allocations_type_check
    CHECK (allocation_type IN ('initial_payment', 'supplier_payment')),
  CONSTRAINT purchase_invoice_payment_allocations_invoice_movement_key
    UNIQUE (purchase_invoice_id, movimiento_financiero_id)
);

CREATE TABLE IF NOT EXISTS public.purchase_invoice_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_invoice_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  estado_original text,
  estado_pago_original text,
  total_original numeric NOT NULL,
  monto_pagado_original numeric NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT purchase_invoice_cancellations_invoice_key UNIQUE (purchase_invoice_id),
  CONSTRAINT purchase_invoice_cancellations_motivo_check
    CHECK (length(trim(motivo)) >= 3)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'purchase_invoice_items_stock_movement_id_fkey'
      AND conrelid = 'public.purchase_invoice_items'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_items
      ADD CONSTRAINT purchase_invoice_items_stock_movement_id_fkey
      FOREIGN KEY (stock_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'stock_movimientos_purchase_invoice_id_fkey'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_purchase_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id) REFERENCES public.purchase_invoices(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'stock_movimientos_purchase_invoice_item_id_fkey'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_purchase_invoice_item_id_fkey
      FOREIGN KEY (purchase_invoice_item_id) REFERENCES public.purchase_invoice_items(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_purchase_invoice_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_purchase_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id) REFERENCES public.purchase_invoices(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'purchase_invoice_payment_allocations_invoice_id_fkey'
      AND conrelid = 'public.purchase_invoice_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_payment_allocations
      ADD CONSTRAINT purchase_invoice_payment_allocations_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id) REFERENCES public.purchase_invoices(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'purchase_invoice_payment_allocations_movement_id_fkey'
      AND conrelid = 'public.purchase_invoice_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_payment_allocations
      ADD CONSTRAINT purchase_invoice_payment_allocations_movement_id_fkey
      FOREIGN KEY (movimiento_financiero_id) REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'purchase_invoice_cancellations_invoice_id_fkey'
      AND conrelid = 'public.purchase_invoice_cancellations'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_cancellations
      ADD CONSTRAINT purchase_invoice_cancellations_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id) REFERENCES public.purchase_invoices(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_purchase_invoice_cancellation_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_purchase_invoice_cancellation_id_fkey
      FOREIGN KEY (purchase_invoice_cancellation_id) REFERENCES public.purchase_invoice_cancellations(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheques_purchase_invoice_id_fkey'
      AND conrelid = 'public.cheques'::regclass
  ) THEN
    ALTER TABLE public.cheques
      ADD CONSTRAINT cheques_purchase_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id) REFERENCES public.purchase_invoices(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_purchase_invoices_estado
  ON public.purchase_invoices (estado);

CREATE INDEX IF NOT EXISTS idx_purchase_invoices_reversion_version
  ON public.purchase_invoices (reversion_version);

CREATE INDEX IF NOT EXISTS idx_purchase_invoice_items_stock_movement_id
  ON public.purchase_invoice_items (stock_movement_id);

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_purchase_invoice_id
  ON public.stock_movimientos (purchase_invoice_id);

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_purchase_invoice_item_id
  ON public.stock_movimientos (purchase_invoice_item_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_purchase_invoice_id
  ON public.movimientos_financieros (purchase_invoice_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_purchase_invoice_cancellation_id
  ON public.movimientos_financieros (purchase_invoice_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_purchase_invoice_payment_allocations_invoice_id
  ON public.purchase_invoice_payment_allocations (purchase_invoice_id);

CREATE INDEX IF NOT EXISTS idx_purchase_invoice_payment_allocations_movement_id
  ON public.purchase_invoice_payment_allocations (movimiento_financiero_id);

CREATE INDEX IF NOT EXISTS idx_cheques_purchase_invoice_id
  ON public.cheques (purchase_invoice_id);

COMMIT;
