BEGIN;

ALTER TABLE public.customer_orders
  ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS cancelled_by text,
  ADD COLUMN IF NOT EXISTS cancel_reason text,
  ADD COLUMN IF NOT EXISTS cancellation_source text,
  ADD COLUMN IF NOT EXISTS cancelled_from_status text;

CREATE TABLE IF NOT EXISTS public.customer_order_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_order_id integer NOT NULL,
  motivo text NOT NULL,
  cancelado_por text NOT NULL,
  cancelado_at timestamp with time zone NOT NULL DEFAULT now(),
  estado_original text NOT NULL,
  cancellation_source text NOT NULL DEFAULT 'manual',
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT customer_order_cancellations_order_key UNIQUE (customer_order_id),
  CONSTRAINT customer_order_cancellations_motivo_check
    CHECK (length(trim(motivo)) >= 3)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'customer_order_cancellations_order_id_fkey'
      AND conrelid = 'public.customer_order_cancellations'::regclass
  ) THEN
    ALTER TABLE public.customer_order_cancellations
      ADD CONSTRAINT customer_order_cancellations_order_id_fkey
      FOREIGN KEY (customer_order_id)
      REFERENCES public.customer_orders(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_customer_orders_estado
  ON public.customer_orders (estado);

CREATE INDEX IF NOT EXISTS idx_customer_orders_cancelled_at
  ON public.customer_orders (cancelled_at);

CREATE INDEX IF NOT EXISTS idx_customer_order_cancellations_order_id
  ON public.customer_order_cancellations (customer_order_id);

UPDATE public.customer_orders
SET cancellation_source = COALESCE(cancellation_source, 'legacy')
WHERE estado = 'cancelado'
  AND cancellation_source IS NULL;

COMMIT;
