BEGIN;

ALTER TABLE public.movimientos_financieros
  ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'Activo',
  ADD COLUMN IF NOT EXISTS reversion_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text,
  ADD COLUMN IF NOT EXISTS financial_movement_cancellation_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'movimientos_financieros_reversion_version_check'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_reversion_version_check
      CHECK (reversion_version IN (0, 1));
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.financial_movement_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movimiento_financiero_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  estado_original text,
  cheque_estado_original text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT financial_movement_cancellations_movement_key
    UNIQUE (movimiento_financiero_id),
  CONSTRAINT financial_movement_cancellations_reason_check
    CHECK (length(trim(motivo)) >= 3)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'financial_movement_cancellations_movement_id_fkey'
      AND conrelid = 'public.financial_movement_cancellations'::regclass
  ) THEN
    ALTER TABLE public.financial_movement_cancellations
      ADD CONSTRAINT financial_movement_cancellations_movement_id_fkey
      FOREIGN KEY (movimiento_financiero_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_financial_cancellation_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_financial_cancellation_id_fkey
      FOREIGN KEY (financial_movement_cancellation_id)
      REFERENCES public.financial_movement_cancellations(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_estado
  ON public.movimientos_financieros (estado);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_reversion_version
  ON public.movimientos_financieros (reversion_version);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_financial_cancellation_id
  ON public.movimientos_financieros (financial_movement_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_financial_movement_cancellations_movement_id
  ON public.financial_movement_cancellations (movimiento_financiero_id);

COMMIT;
