BEGIN;

ALTER TABLE public.movimientos_financieros
  ADD COLUMN IF NOT EXISTS client_payment_cancellation_id integer,
  ADD COLUMN IF NOT EXISTS route_item_id integer;

ALTER TABLE public.sale_payment_allocations
  ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'Activo',
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text,
  ADD COLUMN IF NOT EXISTS client_payment_cancellation_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sale_payment_allocations_estado_check'
      AND conrelid = 'public.sale_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_payment_allocations
      ADD CONSTRAINT sale_payment_allocations_estado_check
      CHECK (estado IN ('Activo', 'Anulado'));
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.client_payment_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movimiento_financiero_id integer NOT NULL,
  reversal_movement_id integer,
  cliente_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  monto_original numeric NOT NULL,
  saldo_cliente_original numeric NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT client_payment_cancellations_movement_key
    UNIQUE (movimiento_financiero_id),
  CONSTRAINT client_payment_cancellations_reason_check
    CHECK (length(trim(motivo)) >= 3),
  CONSTRAINT client_payment_cancellations_amount_check
    CHECK (monto_original > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_payment_cancellations_movement_id_fkey'
      AND conrelid = 'public.client_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.client_payment_cancellations
      ADD CONSTRAINT client_payment_cancellations_movement_id_fkey
      FOREIGN KEY (movimiento_financiero_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_payment_cancellations_reversal_id_fkey'
      AND conrelid = 'public.client_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.client_payment_cancellations
      ADD CONSTRAINT client_payment_cancellations_reversal_id_fkey
      FOREIGN KEY (reversal_movement_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_payment_cancellations_customer_id_fkey'
      AND conrelid = 'public.client_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.client_payment_cancellations
      ADD CONSTRAINT client_payment_cancellations_customer_id_fkey
      FOREIGN KEY (cliente_id)
      REFERENCES public.clientes(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_client_payment_cancellation_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_client_payment_cancellation_id_fkey
      FOREIGN KEY (client_payment_cancellation_id)
      REFERENCES public.client_payment_cancellations(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sale_payment_allocations_client_payment_cancellation_id_fkey'
      AND conrelid = 'public.sale_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.sale_payment_allocations
      ADD CONSTRAINT sale_payment_allocations_client_payment_cancellation_id_fkey
      FOREIGN KEY (client_payment_cancellation_id)
      REFERENCES public.client_payment_cancellations(id);
  END IF;

  IF to_regclass('public.route_items') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_route_item_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_route_item_id_fkey
      FOREIGN KEY (route_item_id)
      REFERENCES public.route_items(id);
  END IF;
END
$$;

UPDATE public.sale_payment_allocations
SET estado = 'Activo'
WHERE estado IS NULL;

-- Las cobranzas históricas conservan reversion_version = 0.
-- Solo las cobranzas creadas por el código de esta fase quedan habilitadas para anulación automática.

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_client_payment_cancellation_id
  ON public.movimientos_financieros (client_payment_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_route_item_id
  ON public.movimientos_financieros (route_item_id);

CREATE INDEX IF NOT EXISTS idx_sale_payment_allocations_estado
  ON public.sale_payment_allocations (estado);

CREATE INDEX IF NOT EXISTS idx_sale_payment_allocations_client_payment_cancellation_id
  ON public.sale_payment_allocations (client_payment_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_client_payment_cancellations_movement_id
  ON public.client_payment_cancellations (movimiento_financiero_id);

CREATE INDEX IF NOT EXISTS idx_client_payment_cancellations_customer_id
  ON public.client_payment_cancellations (cliente_id);

COMMIT;
