BEGIN;

ALTER TABLE public.cheques
  ADD COLUMN IF NOT EXISTS estado_actualizado_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS estado_actualizado_por text,
  ADD COLUMN IF NOT EXISTS ultimo_cambio_estado_id integer;

UPDATE public.cheques
SET estado = 'en_cartera'
WHERE estado IS NULL OR trim(estado) = '';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'cheques_estado_check'
      AND conrelid = 'public.cheques'::regclass
  ) THEN
    ALTER TABLE public.cheques
      ADD CONSTRAINT cheques_estado_check
      CHECK (estado IN (
        'en_cartera',
        'depositado',
        'entregado_proveedor',
        'cobrado',
        'rechazado',
        'anulado'
      ));
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.cheque_status_changes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cheque_id integer NOT NULL,
  estado_anterior text NOT NULL,
  estado_nuevo text NOT NULL,
  motivo text NOT NULL,
  cambiado_por text NOT NULL,
  cambiado_at timestamp with time zone NOT NULL DEFAULT now(),
  origen text NOT NULL DEFAULT 'manual',
  financial_movement_id integer,
  revertido_at timestamp with time zone,
  revertido_por text,
  reversion_motivo text,
  reversal_movement_id integer,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT cheque_status_changes_reason_check
    CHECK (length(trim(motivo)) >= 3),
  CONSTRAINT cheque_status_changes_states_check
    CHECK (
      estado_anterior IN ('en_cartera', 'depositado', 'entregado_proveedor', 'cobrado', 'rechazado', 'anulado')
      AND estado_nuevo IN ('en_cartera', 'depositado', 'entregado_proveedor', 'cobrado', 'rechazado', 'anulado')
      AND estado_anterior <> estado_nuevo
    )
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_status_changes_cheque_id_fkey'
      AND conrelid = 'public.cheque_status_changes'::regclass
  ) THEN
    ALTER TABLE public.cheque_status_changes
      ADD CONSTRAINT cheque_status_changes_cheque_id_fkey
      FOREIGN KEY (cheque_id)
      REFERENCES public.cheques(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_status_changes_financial_movement_id_fkey'
      AND conrelid = 'public.cheque_status_changes'::regclass
  ) THEN
    ALTER TABLE public.cheque_status_changes
      ADD CONSTRAINT cheque_status_changes_financial_movement_id_fkey
      FOREIGN KEY (financial_movement_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_status_changes_reversal_movement_id_fkey'
      AND conrelid = 'public.cheque_status_changes'::regclass
  ) THEN
    ALTER TABLE public.cheque_status_changes
      ADD CONSTRAINT cheque_status_changes_reversal_movement_id_fkey
      FOREIGN KEY (reversal_movement_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheques_ultimo_cambio_estado_id_fkey'
      AND conrelid = 'public.cheques'::regclass
  ) THEN
    ALTER TABLE public.cheques
      ADD CONSTRAINT cheques_ultimo_cambio_estado_id_fkey
      FOREIGN KEY (ultimo_cambio_estado_id)
      REFERENCES public.cheque_status_changes(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_cheques_estado
  ON public.cheques (estado);

CREATE INDEX IF NOT EXISTS idx_cheques_ultimo_cambio_estado_id
  ON public.cheques (ultimo_cambio_estado_id);

CREATE INDEX IF NOT EXISTS idx_cheque_status_changes_cheque_id
  ON public.cheque_status_changes (cheque_id, cambiado_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_cheque_status_changes_financial_movement_id
  ON public.cheque_status_changes (financial_movement_id);

COMMIT;
