BEGIN;

ALTER TABLE public.cheques
  ADD COLUMN IF NOT EXISTS financial_movement_id integer;

CREATE TABLE IF NOT EXISTS public.cheque_rejection_allocations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cheque_status_change_id integer NOT NULL,
  cheque_id integer NOT NULL,
  sale_payment_allocation_id integer NOT NULL,
  sale_id integer NOT NULL,
  monto numeric(14,2) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reverted_at timestamp with time zone,
  reverted_by text,
  reversion_reason text,
  CONSTRAINT cheque_rejection_allocations_amount_check CHECK (monto > 0),
  CONSTRAINT cheque_rejection_allocations_unique UNIQUE (cheque_status_change_id, sale_payment_allocation_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheques_financial_movement_id_fkey'
      AND conrelid = 'public.cheques'::regclass
  ) THEN
    ALTER TABLE public.cheques
      ADD CONSTRAINT cheques_financial_movement_id_fkey
      FOREIGN KEY (financial_movement_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_rejection_allocations_change_fkey'
      AND conrelid = 'public.cheque_rejection_allocations'::regclass
  ) THEN
    ALTER TABLE public.cheque_rejection_allocations
      ADD CONSTRAINT cheque_rejection_allocations_change_fkey
      FOREIGN KEY (cheque_status_change_id)
      REFERENCES public.cheque_status_changes(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_rejection_allocations_cheque_fkey'
      AND conrelid = 'public.cheque_rejection_allocations'::regclass
  ) THEN
    ALTER TABLE public.cheque_rejection_allocations
      ADD CONSTRAINT cheque_rejection_allocations_cheque_fkey
      FOREIGN KEY (cheque_id)
      REFERENCES public.cheques(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_rejection_allocations_payment_allocation_fkey'
      AND conrelid = 'public.cheque_rejection_allocations'::regclass
  ) THEN
    ALTER TABLE public.cheque_rejection_allocations
      ADD CONSTRAINT cheque_rejection_allocations_payment_allocation_fkey
      FOREIGN KEY (sale_payment_allocation_id)
      REFERENCES public.sale_payment_allocations(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cheque_rejection_allocations_sale_fkey'
      AND conrelid = 'public.cheque_rejection_allocations'::regclass
  ) THEN
    ALTER TABLE public.cheque_rejection_allocations
      ADD CONSTRAINT cheque_rejection_allocations_sale_fkey
      FOREIGN KEY (sale_id)
      REFERENCES public.sales(id);
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_cheques_financial_movement_unique
  ON public.cheques (financial_movement_id)
  WHERE financial_movement_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cheque_rejection_allocations_change
  ON public.cheque_rejection_allocations (cheque_status_change_id);

CREATE INDEX IF NOT EXISTS idx_cheque_rejection_allocations_cheque
  ON public.cheque_rejection_allocations (cheque_id);

COMMIT;
