BEGIN;

ALTER TABLE public.movimientos_financieros
  ADD COLUMN IF NOT EXISTS supplier_payment_cancellation_id integer;

ALTER TABLE public.purchase_invoice_payment_allocations
  ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'Activo',
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text,
  ADD COLUMN IF NOT EXISTS supplier_payment_cancellation_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'purchase_invoice_payment_allocations_estado_check'
      AND conrelid = 'public.purchase_invoice_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_payment_allocations
      ADD CONSTRAINT purchase_invoice_payment_allocations_estado_check
      CHECK (estado IN ('Activo', 'Anulado'));
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.supplier_payment_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movimiento_financiero_id integer NOT NULL,
  reversal_movement_id integer,
  purchase_invoice_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  monto_original numeric NOT NULL,
  monto_pagado_original numeric NOT NULL,
  estado_pago_original text,
  cheque_id integer,
  cheque_estado_original text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT supplier_payment_cancellations_movement_key
    UNIQUE (movimiento_financiero_id),
  CONSTRAINT supplier_payment_cancellations_reason_check
    CHECK (length(trim(motivo)) >= 3),
  CONSTRAINT supplier_payment_cancellations_amount_check
    CHECK (monto_original > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_payment_cancellations_movement_id_fkey'
      AND conrelid = 'public.supplier_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.supplier_payment_cancellations
      ADD CONSTRAINT supplier_payment_cancellations_movement_id_fkey
      FOREIGN KEY (movimiento_financiero_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_payment_cancellations_reversal_id_fkey'
      AND conrelid = 'public.supplier_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.supplier_payment_cancellations
      ADD CONSTRAINT supplier_payment_cancellations_reversal_id_fkey
      FOREIGN KEY (reversal_movement_id)
      REFERENCES public.movimientos_financieros(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_payment_cancellations_invoice_id_fkey'
      AND conrelid = 'public.supplier_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.supplier_payment_cancellations
      ADD CONSTRAINT supplier_payment_cancellations_invoice_id_fkey
      FOREIGN KEY (purchase_invoice_id)
      REFERENCES public.purchase_invoices(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_payment_cancellations_cheque_id_fkey'
      AND conrelid = 'public.supplier_payment_cancellations'::regclass
  ) THEN
    ALTER TABLE public.supplier_payment_cancellations
      ADD CONSTRAINT supplier_payment_cancellations_cheque_id_fkey
      FOREIGN KEY (cheque_id)
      REFERENCES public.cheques(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'movimientos_financieros_supplier_payment_cancellation_id_fkey'
      AND conrelid = 'public.movimientos_financieros'::regclass
  ) THEN
    ALTER TABLE public.movimientos_financieros
      ADD CONSTRAINT movimientos_financieros_supplier_payment_cancellation_id_fkey
      FOREIGN KEY (supplier_payment_cancellation_id)
      REFERENCES public.supplier_payment_cancellations(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pia_supplier_payment_cancellation_id_fkey'
      AND conrelid = 'public.purchase_invoice_payment_allocations'::regclass
  ) THEN
    ALTER TABLE public.purchase_invoice_payment_allocations
      ADD CONSTRAINT pia_supplier_payment_cancellation_id_fkey
      FOREIGN KEY (supplier_payment_cancellation_id)
      REFERENCES public.supplier_payment_cancellations(id);
  END IF;
END
$$;

UPDATE public.purchase_invoice_payment_allocations
SET estado = 'Activo'
WHERE estado IS NULL;

-- Los pagos a proveedores históricos conservan reversion_version = 0.
-- Solo los pagos nuevos creados por esta fase quedan habilitados para anulación automática.

CREATE INDEX IF NOT EXISTS idx_movimientos_financieros_supplier_payment_cancellation_id
  ON public.movimientos_financieros (supplier_payment_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_purchase_invoice_payment_allocations_estado
  ON public.purchase_invoice_payment_allocations (estado);

CREATE INDEX IF NOT EXISTS idx_pia_supplier_payment_cancellation_id
  ON public.purchase_invoice_payment_allocations (supplier_payment_cancellation_id);

CREATE INDEX IF NOT EXISTS idx_supplier_payment_cancellations_movement_id
  ON public.supplier_payment_cancellations (movimiento_financiero_id);

CREATE INDEX IF NOT EXISTS idx_supplier_payment_cancellations_invoice_id
  ON public.supplier_payment_cancellations (purchase_invoice_id);

COMMIT;
