BEGIN;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS reversion_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anulada_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS anulada_por text,
  ADD COLUMN IF NOT EXISTS anulacion_motivo text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'stock_movimientos_reversion_version_check'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_reversion_version_check
      CHECK (reversion_version IN (0, 1));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'stock_movimientos_anulacion_motivo_check'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movimientos_anulacion_motivo_check
      CHECK (anulacion_motivo IS NULL OR length(trim(anulacion_motivo)) >= 3);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.stock_movement_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_movement_id integer NOT NULL,
  reversal_movement_id integer NOT NULL,
  product_id integer NOT NULL,
  motivo text NOT NULL,
  anulada_por text NOT NULL,
  anulada_at timestamp with time zone NOT NULL DEFAULT now(),
  stock_before numeric NOT NULL,
  stock_after numeric NOT NULL,
  original_type text NOT NULL,
  original_reason text,
  quantity numeric NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT stock_movement_cancellations_movement_key UNIQUE (stock_movement_id),
  CONSTRAINT stock_movement_cancellations_reversal_key UNIQUE (reversal_movement_id),
  CONSTRAINT stock_movement_cancellations_reason_check CHECK (length(trim(motivo)) >= 3),
  CONSTRAINT stock_movement_cancellations_quantity_check CHECK (quantity > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'smc_stock_movement_id_fkey'
      AND conrelid = 'public.stock_movement_cancellations'::regclass
  ) THEN
    ALTER TABLE public.stock_movement_cancellations
      ADD CONSTRAINT smc_stock_movement_id_fkey
      FOREIGN KEY (stock_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'smc_reversal_movement_id_fkey'
      AND conrelid = 'public.stock_movement_cancellations'::regclass
  ) THEN
    ALTER TABLE public.stock_movement_cancellations
      ADD CONSTRAINT smc_reversal_movement_id_fkey
      FOREIGN KEY (reversal_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'smc_product_id_fkey'
      AND conrelid = 'public.stock_movement_cancellations'::regclass
  ) THEN
    ALTER TABLE public.stock_movement_cancellations
      ADD CONSTRAINT smc_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES public.products(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_stock_movements_product_date
  ON public.stock_movimientos (product_id, fecha_ingreso DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_stock_movement_cancellations_product
  ON public.stock_movement_cancellations (product_id, anulada_at DESC);

COMMIT;
