BEGIN;

ALTER TABLE public.supplier_orders
  ADD COLUMN IF NOT EXISTS delivery_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivered_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS delivered_by text,
  ADD COLUMN IF NOT EXISTS delivered_from_status text,
  ADD COLUMN IF NOT EXISTS delivery_reverted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS delivery_reverted_by text,
  ADD COLUMN IF NOT EXISTS delivery_revert_reason text;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS supplier_order_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_delivery_version_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_delivery_version_check
      CHECK (delivery_version IN (0, 1));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_delivery_revert_reason_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_delivery_revert_reason_check
      CHECK (delivery_revert_reason IS NULL OR length(trim(delivery_revert_reason)) >= 3);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'stock_movements_supplier_order_fkey'
      AND conrelid = 'public.stock_movimientos'::regclass
  ) THEN
    ALTER TABLE public.stock_movimientos
      ADD CONSTRAINT stock_movements_supplier_order_fkey
      FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.supplier_order_deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_order_id integer NOT NULL,
  delivery_mode text NOT NULL,
  previous_status text NOT NULL,
  sale_id_before integer,
  sale_id_after integer,
  customer_order_id integer,
  delivered_by text NOT NULL,
  delivered_at timestamp with time zone NOT NULL DEFAULT now(),
  reverted_at timestamp with time zone,
  reverted_by text,
  revert_reason text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT supplier_order_deliveries_mode_check
    CHECK (delivery_mode IN ('stock_only', 'linked_sale', 'created_sale')),
  CONSTRAINT supplier_order_deliveries_revert_reason_check
    CHECK (revert_reason IS NULL OR length(trim(revert_reason)) >= 3)
);

CREATE TABLE IF NOT EXISTS public.supplier_order_delivery_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity numeric NOT NULL,
  unit_cost numeric NOT NULL DEFAULT 0,
  ingress_movement_id integer NOT NULL,
  egress_movement_id integer,
  CONSTRAINT supplier_order_delivery_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT supplier_order_delivery_items_ingress_key UNIQUE (ingress_movement_id),
  CONSTRAINT supplier_order_delivery_items_egress_key UNIQUE (egress_movement_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sod_supplier_order_id_fkey'
      AND conrelid = 'public.supplier_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_deliveries
      ADD CONSTRAINT sod_supplier_order_id_fkey
      FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sod_sale_before_fkey'
      AND conrelid = 'public.supplier_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_deliveries
      ADD CONSTRAINT sod_sale_before_fkey
      FOREIGN KEY (sale_id_before) REFERENCES public.sales(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sod_sale_after_fkey'
      AND conrelid = 'public.supplier_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_deliveries
      ADD CONSTRAINT sod_sale_after_fkey
      FOREIGN KEY (sale_id_after) REFERENCES public.sales(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sod_customer_order_id_fkey'
      AND conrelid = 'public.supplier_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_deliveries
      ADD CONSTRAINT sod_customer_order_id_fkey
      FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sodi_delivery_id_fkey'
      AND conrelid = 'public.supplier_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_delivery_items
      ADD CONSTRAINT sodi_delivery_id_fkey
      FOREIGN KEY (delivery_id) REFERENCES public.supplier_order_deliveries(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sodi_product_id_fkey'
      AND conrelid = 'public.supplier_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_delivery_items
      ADD CONSTRAINT sodi_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES public.products(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sodi_ingress_movement_fkey'
      AND conrelid = 'public.supplier_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_delivery_items
      ADD CONSTRAINT sodi_ingress_movement_fkey
      FOREIGN KEY (ingress_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sodi_egress_movement_fkey'
      AND conrelid = 'public.supplier_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.supplier_order_delivery_items
      ADD CONSTRAINT sodi_egress_movement_fkey
      FOREIGN KEY (egress_movement_id) REFERENCES public.stock_movimientos(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_supplier_order_deliveries_order
  ON public.supplier_order_deliveries (supplier_order_id, delivered_at DESC);

CREATE INDEX IF NOT EXISTS idx_supplier_order_delivery_items_delivery
  ON public.supplier_order_delivery_items (delivery_id);

CREATE INDEX IF NOT EXISTS idx_stock_movements_supplier_order
  ON public.stock_movimientos (supplier_order_id, fecha_ingreso DESC, id DESC);

COMMIT;
