BEGIN;

ALTER TABLE public.customer_orders
  ADD COLUMN IF NOT EXISTS delivery_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivered_by text,
  ADD COLUMN IF NOT EXISTS delivered_from_status text,
  ADD COLUMN IF NOT EXISTS delivery_reverted_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS delivery_reverted_by text,
  ADD COLUMN IF NOT EXISTS delivery_revert_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_delivery_version_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_delivery_version_check
      CHECK (delivery_version IN (0, 1));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_delivery_revert_reason_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_delivery_revert_reason_check
      CHECK (delivery_revert_reason IS NULL OR length(trim(delivery_revert_reason)) >= 3);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.customer_order_deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_order_id integer NOT NULL,
  sale_id integer NOT NULL,
  previous_status text NOT NULL,
  delivered_by text NOT NULL,
  delivered_at timestamp with time zone NOT NULL DEFAULT now(),
  reverted_at timestamp with time zone,
  reverted_by text,
  revert_reason text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT customer_order_deliveries_revert_reason_check
    CHECK (revert_reason IS NULL OR length(trim(revert_reason)) >= 3)
);

CREATE TABLE IF NOT EXISTS public.customer_order_delivery_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id integer NOT NULL,
  customer_order_item_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity numeric NOT NULL,
  sale_item_id integer NOT NULL,
  CONSTRAINT customer_order_delivery_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT customer_order_delivery_items_sale_item_key UNIQUE (sale_item_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cod_customer_order_id_fkey'
      AND conrelid = 'public.customer_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.customer_order_deliveries
      ADD CONSTRAINT cod_customer_order_id_fkey
      FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cod_sale_id_fkey'
      AND conrelid = 'public.customer_order_deliveries'::regclass
  ) THEN
    ALTER TABLE public.customer_order_deliveries
      ADD CONSTRAINT cod_sale_id_fkey
      FOREIGN KEY (sale_id) REFERENCES public.sales(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'codi_delivery_id_fkey'
      AND conrelid = 'public.customer_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.customer_order_delivery_items
      ADD CONSTRAINT codi_delivery_id_fkey
      FOREIGN KEY (delivery_id) REFERENCES public.customer_order_deliveries(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'codi_order_item_id_fkey'
      AND conrelid = 'public.customer_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.customer_order_delivery_items
      ADD CONSTRAINT codi_order_item_id_fkey
      FOREIGN KEY (customer_order_item_id) REFERENCES public.customer_order_items(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'codi_product_id_fkey'
      AND conrelid = 'public.customer_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.customer_order_delivery_items
      ADD CONSTRAINT codi_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES public.products(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'codi_sale_item_id_fkey'
      AND conrelid = 'public.customer_order_delivery_items'::regclass
  ) THEN
    ALTER TABLE public.customer_order_delivery_items
      ADD CONSTRAINT codi_sale_item_id_fkey
      FOREIGN KEY (sale_item_id) REFERENCES public.sale_items(id);
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uidx_cod_active_order
  ON public.customer_order_deliveries (customer_order_id)
  WHERE reverted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_cod_sale
  ON public.customer_order_deliveries (sale_id);

CREATE INDEX IF NOT EXISTS idx_codi_delivery
  ON public.customer_order_delivery_items (delivery_id);

COMMIT;
