BEGIN;

ALTER TABLE public.customer_orders
  ADD COLUMN IF NOT EXISTS rejection_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rejected_by text,
  ADD COLUMN IF NOT EXISTS rejected_from_status text,
  ADD COLUMN IF NOT EXISTS reopened_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS reopened_by text,
  ADD COLUMN IF NOT EXISTS reopen_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'customer_orders_rejection_version_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_rejection_version_check
      CHECK (rejection_version >= 0);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'customer_orders_reopen_reason_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_reopen_reason_check
      CHECK (reopened_at IS NULL OR length(trim(COALESCE(reopen_reason, ''))) >= 3);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.customer_order_rejections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_order_id integer NOT NULL,
  version integer NOT NULL,
  estado_anterior text NOT NULL,
  motivo text NOT NULL,
  admin_notes_before text,
  admin_notes_after text,
  rejected_by text NOT NULL,
  rejected_at timestamp with time zone NOT NULL DEFAULT now(),
  reopened_at timestamp with time zone,
  reopened_by text,
  reopen_reason text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT customer_order_rejections_order_version_key UNIQUE (customer_order_id, version),
  CONSTRAINT customer_order_rejections_version_check CHECK (version > 0),
  CONSTRAINT customer_order_rejections_motivo_check CHECK (length(trim(motivo)) >= 3),
  CONSTRAINT customer_order_rejections_reopen_reason_check
    CHECK (reopened_at IS NULL OR length(trim(COALESCE(reopen_reason, ''))) >= 3)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'customer_order_rejections_order_id_fkey'
      AND conrelid = 'public.customer_order_rejections'::regclass
  ) THEN
    ALTER TABLE public.customer_order_rejections
      ADD CONSTRAINT customer_order_rejections_order_id_fkey
      FOREIGN KEY (customer_order_id)
      REFERENCES public.customer_orders(id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_customer_order_rejections_order_id
  ON public.customer_order_rejections (customer_order_id, version DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_order_rejections_active
  ON public.customer_order_rejections (customer_order_id)
  WHERE reopened_at IS NULL;

COMMIT;
