BEGIN;

ALTER TABLE public.supplier_orders
  ADD COLUMN IF NOT EXISTS status_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status_changed_at timestamptz,
  ADD COLUMN IF NOT EXISTS status_changed_by text,
  ADD COLUMN IF NOT EXISTS status_changed_from text,
  ADD COLUMN IF NOT EXISTS status_last_action text,
  ADD COLUMN IF NOT EXISTS status_last_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_status_version_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_status_version_check
      CHECK (status_version >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_status_last_action_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_status_last_action_check
      CHECK (status_last_action IS NULL OR status_last_action IN ('advance', 'reopen'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_status_last_reason_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_status_last_reason_check
      CHECK (
        status_last_reason IS NULL
        OR char_length(btrim(status_last_reason)) BETWEEN 3 AND 500
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.supplier_order_status_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_order_id integer NOT NULL,
  version integer NOT NULL,
  action text NOT NULL,
  from_status text NOT NULL,
  to_status text NOT NULL,
  reason text,
  changed_by text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT supplier_order_status_history_order_fkey
    FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id),
  CONSTRAINT supplier_order_status_history_version_check CHECK (version > 0),
  CONSTRAINT supplier_order_status_history_action_check CHECK (action IN ('advance', 'reopen')),
  CONSTRAINT supplier_order_status_history_from_status_check
    CHECK (from_status IN ('pendiente', 'pedido_realizado', 'auditar_pedido')),
  CONSTRAINT supplier_order_status_history_to_status_check
    CHECK (to_status IN ('pendiente', 'pedido_realizado', 'auditar_pedido')),
  CONSTRAINT supplier_order_status_history_transition_check CHECK (
    (action = 'advance' AND (
      (from_status = 'pendiente' AND to_status = 'pedido_realizado') OR
      (from_status = 'pedido_realizado' AND to_status = 'auditar_pedido')
    )) OR
    (action = 'reopen' AND (
      (from_status = 'pedido_realizado' AND to_status = 'pendiente') OR
      (from_status = 'auditar_pedido' AND to_status = 'pedido_realizado')
    ))
  ),
  CONSTRAINT supplier_order_status_history_reason_check CHECK (
    (action = 'advance' AND reason IS NULL) OR
    (
      action = 'reopen'
      AND reason IS NOT NULL
      AND char_length(btrim(reason)) BETWEEN 3 AND 500
    )
  ),
  CONSTRAINT supplier_order_status_history_unique_version UNIQUE (supplier_order_id, version)
);

CREATE INDEX IF NOT EXISTS idx_supplier_order_status_history_order
  ON public.supplier_order_status_history (supplier_order_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_supplier_orders_status_changed_at
  ON public.supplier_orders (status_changed_at DESC)
  WHERE status_changed_at IS NOT NULL;

COMMIT;
