BEGIN;

ALTER TABLE public.supplier_orders
  ADD COLUMN IF NOT EXISTS content_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS content_changed_at timestamptz,
  ADD COLUMN IF NOT EXISTS content_changed_by text,
  ADD COLUMN IF NOT EXISTS content_change_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_content_version_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_content_version_check
      CHECK (content_version >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'supplier_orders_content_change_reason_check'
      AND conrelid = 'public.supplier_orders'::regclass
  ) THEN
    ALTER TABLE public.supplier_orders
      ADD CONSTRAINT supplier_orders_content_change_reason_check
      CHECK (
        content_change_reason IS NULL
        OR char_length(btrim(content_change_reason)) BETWEEN 3 AND 500
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.supplier_order_content_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_order_id integer NOT NULL,
  version integer NOT NULL,
  status_at_change text NOT NULL,
  reason text NOT NULL,
  changed_by text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  before_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  after_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT supplier_order_content_history_order_fkey
    FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id),
  CONSTRAINT supplier_order_content_history_version_check CHECK (version > 0),
  CONSTRAINT supplier_order_content_history_status_check CHECK (status_at_change = 'auditar_pedido'),
  CONSTRAINT supplier_order_content_history_reason_check
    CHECK (char_length(btrim(reason)) BETWEEN 3 AND 500),
  CONSTRAINT supplier_order_content_history_before_snapshot_check
    CHECK (jsonb_typeof(before_snapshot) = 'object'),
  CONSTRAINT supplier_order_content_history_after_snapshot_check
    CHECK (jsonb_typeof(after_snapshot) = 'object'),
  CONSTRAINT supplier_order_content_history_unique_version UNIQUE (supplier_order_id, version)
);

CREATE INDEX IF NOT EXISTS idx_supplier_order_content_history_order
  ON public.supplier_order_content_history (supplier_order_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_supplier_orders_content_changed_at
  ON public.supplier_orders (content_changed_at DESC)
  WHERE content_changed_at IS NOT NULL;

COMMIT;
