BEGIN;

ALTER TABLE public.customer_orders
  ADD COLUMN IF NOT EXISTS approval_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS approved_by text,
  ADD COLUMN IF NOT EXISTS approved_from_status text,
  ADD COLUMN IF NOT EXISTS aprobado_at timestamp with time zone;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_approval_version_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_approval_version_check
      CHECK (approval_version >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_approved_from_status_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_approved_from_status_check
      CHECK (approved_from_status IS NULL OR approved_from_status = 'pendiente_aprobacion');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.customer_order_approvals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_order_id integer NOT NULL,
  version integer NOT NULL,
  previous_status text NOT NULL,
  subtotal numeric NOT NULL,
  discount_type text NOT NULL,
  discount_value numeric NOT NULL,
  discount_amount numeric NOT NULL,
  total_final numeric NOT NULL,
  approved_by text NOT NULL,
  approved_at timestamp with time zone NOT NULL DEFAULT now(),
  supplier_order_id integer,
  order_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  items_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  shortages_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT customer_order_approvals_order_fkey
    FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders(id),
  CONSTRAINT customer_order_approvals_supplier_order_fkey
    FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id),
  CONSTRAINT customer_order_approvals_unique_version
    UNIQUE (customer_order_id, version),
  CONSTRAINT customer_order_approvals_version_check CHECK (version > 0),
  CONSTRAINT customer_order_approvals_previous_status_check
    CHECK (previous_status = 'pendiente_aprobacion'),
  CONSTRAINT customer_order_approvals_discount_type_check
    CHECK (discount_type IN ('none', 'percentage', 'fixed')),
  CONSTRAINT customer_order_approvals_amounts_check
    CHECK (
      subtotal >= 0
      AND discount_value >= 0
      AND discount_amount >= 0
      AND total_final >= 0
    ),
  CONSTRAINT customer_order_approvals_order_snapshot_check
    CHECK (jsonb_typeof(order_snapshot) = 'object'),
  CONSTRAINT customer_order_approvals_items_snapshot_check
    CHECK (jsonb_typeof(items_snapshot) = 'array'),
  CONSTRAINT customer_order_approvals_shortages_snapshot_check
    CHECK (jsonb_typeof(shortages_snapshot) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_customer_order_approvals_order
  ON public.customer_order_approvals (customer_order_id, version DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_order_approvals_supplier_order
  ON public.customer_order_approvals (supplier_order_id)
  WHERE supplier_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customer_orders_approved_at
  ON public.customer_orders (aprobado_at DESC)
  WHERE aprobado_at IS NOT NULL;

COMMIT;
