BEGIN;

ALTER TABLE public.customer_orders
  ADD COLUMN IF NOT EXISTS content_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS content_changed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS content_changed_by text,
  ADD COLUMN IF NOT EXISTS content_change_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_content_version_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_content_version_check
      CHECK (content_version >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_orders_content_change_reason_check'
      AND conrelid = 'public.customer_orders'::regclass
  ) THEN
    ALTER TABLE public.customer_orders
      ADD CONSTRAINT customer_orders_content_change_reason_check
      CHECK (
        content_change_reason IS NULL
        OR char_length(btrim(content_change_reason)) BETWEEN 3 AND 500
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.customer_order_content_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_order_id integer NOT NULL,
  version integer NOT NULL,
  status_at_change text NOT NULL,
  reason text NOT NULL,
  changed_by text NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  order_before_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  items_before_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  order_after_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  items_after_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT customer_order_content_history_order_fkey
    FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders(id),
  CONSTRAINT customer_order_content_history_unique_version
    UNIQUE (customer_order_id, version),
  CONSTRAINT customer_order_content_history_version_check
    CHECK (version > 0),
  CONSTRAINT customer_order_content_history_status_check
    CHECK (status_at_change = 'pendiente_aprobacion'),
  CONSTRAINT customer_order_content_history_reason_check
    CHECK (char_length(btrim(reason)) BETWEEN 3 AND 500),
  CONSTRAINT customer_order_content_history_before_order_check
    CHECK (jsonb_typeof(order_before_snapshot) = 'object'),
  CONSTRAINT customer_order_content_history_before_items_check
    CHECK (jsonb_typeof(items_before_snapshot) = 'array'),
  CONSTRAINT customer_order_content_history_after_order_check
    CHECK (jsonb_typeof(order_after_snapshot) = 'object'),
  CONSTRAINT customer_order_content_history_after_items_check
    CHECK (jsonb_typeof(items_after_snapshot) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_customer_order_content_history_order
  ON public.customer_order_content_history (customer_order_id, version DESC);

CREATE INDEX IF NOT EXISTS idx_customer_orders_content_changed_at
  ON public.customer_orders (content_changed_at DESC)
  WHERE content_changed_at IS NOT NULL;

COMMIT;
