BEGIN;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS permissions_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS permissions_changed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS permissions_changed_by text,
  ADD COLUMN IF NOT EXISTS permissions_change_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_permissions_version_check'
      AND conrelid = 'public.users'::regclass
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_permissions_version_check
      CHECK (permissions_version >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_permissions_change_reason_check'
      AND conrelid = 'public.users'::regclass
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_permissions_change_reason_check
      CHECK (
        permissions_change_reason IS NULL
        OR char_length(btrim(permissions_change_reason)) BETWEEN 3 AND 500
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.user_permission_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  version integer NOT NULL,
  reason text NOT NULL,
  changed_by_user_id integer,
  changed_by text NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  permissions_before_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  permissions_after_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT user_permission_history_user_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_permission_history_actor_fkey
    FOREIGN KEY (changed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT user_permission_history_unique_version
    UNIQUE (user_id, version),
  CONSTRAINT user_permission_history_version_check
    CHECK (version > 0),
  CONSTRAINT user_permission_history_reason_check
    CHECK (char_length(btrim(reason)) BETWEEN 3 AND 500),
  CONSTRAINT user_permission_history_before_check
    CHECK (jsonb_typeof(permissions_before_snapshot) = 'array'),
  CONSTRAINT user_permission_history_after_check
    CHECK (jsonb_typeof(permissions_after_snapshot) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_user_permission_history_user
  ON public.user_permission_history (user_id, version DESC);

CREATE INDEX IF NOT EXISTS idx_users_permissions_changed_at
  ON public.users (permissions_changed_at DESC)
  WHERE permissions_changed_at IS NOT NULL;

COMMIT;
